#!/usr/bin/env node

var val = require("./validateString");
if (typeof process.argv[2] === "undefined") {
    console.error("Error: no text to rank");
    process.exit(1);
}
if (process.argv[2] === "--help") {
    console.log("");
    console.log("\tUsage: zookin-score <text>");
    console.log("\tOutputs a score ranking the text in likeleyhood of it being a valid solution");
    console.log("\tScores range from 0 to INF and are based on bigrams and word occurences in English");
    console.log();
    process.exit(0);
}
console.log("'\033[33m" + process.argv[2] + "\033[0m' has a score of \033[31m" + val(process.argv[2]) + "\033[0m");
